<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function showPlayerResult($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Team t
              JOIN AppBundle:Player r
              WHERE t.id = r.team
              AND t.id = :id1'
            )->setParameter('id1', $id)
            ->getResult();
    }
}
