<?php

namespace AppBundle\Repository;

/**
 * ResultGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultGameRepository extends \Doctrine\ORM\EntityRepository
{
}
