<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;


/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function showTeamResult()
    {
        return $this->getEntityManager()
            ->createQuery(
              "SELECT t, r FROM AppBundle:Team t
               JOIN t.results r
               ORDER BY r.points DESC"
            );
       //     ->getResult();
        /*return $this->createQueryBuilder('t')
            ->select('t, r')
            ->join('t.results', 'r')
            ->orderBy('r.points', 'DESC')
            ->getQuery()
            ->getResult();*/
    }

    /**
     * @return array
     */
    public function showTeamASC()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t FROM AppBundle:Team t
                 ORDER BY t.country ASC"
            )
            ->getResult();
    }

    /**
     * @param $id
     * @return array
     */
    public function showTeamId($data)
    {
        return $this->createQueryBuilder('t')
            ->select('t, p, c, cn')
            ->join('t.players', 'p')
            ->join('t.coaches', 'c')
            ->join('t.countries', 'cn')
            ->where('t.country LIKE :data')
            ->orWhere('p.lastName LIKE :data')
            ->orWhere('c.lastName LIKE :data')
            ->orWhere('cn.fullTitle LIKE :data')
            ->setParameter('data', '%'.$data.'%')
            ->getQuery()
            ->getResult();
    }

    public function findAllAjax($data)
    {
        return $this->createQueryBuilder('t')
            ->select('t, p, c, cn')
            ->join('t.players', 'p')
            ->join('t.coaches', 'c')
            ->join('t.countries', 'cn')
            ->where('t.country LIKE :data')
            ->orWhere('p.lastName LIKE :data')
            ->orWhere('c.lastName LIKE :data')
            ->orWhere('cn.fullTitle LIKE :data')
            ->setParameter('data', '%'.$data.'%')
            ->getQuery()
            ->getResult();
    }


}
