<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function showTeamResult()
    {
        return $this->getEntityManager()
            ->createQuery(
              'SELECT t FROM AppBundle:Team t
              JOIN AppBundle:ResultGame r
              WHERE t.id = r.team
              ORDER BY r.points DESC'
            )
            ->getResult();
    }
}
