app:
    resource: "@AppBundle/Controller/"
    type:     annotation

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template: @App/static/about.html.twig

